name: First workflow
on: push

jobs:
 build: 
   runs-on: ubuntu-latest
    
   steps:
    - uses:  actions/checkout@3
    
    - name: Run a sample github action
      run: echo "this workflow run successfully for this action"
